server:
  port: 8088

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/bili

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bili?serverTimezone=GMT%2B8
    username: root
    password: 123456

  redis:
    host: localhost
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms